web:
    container_name: voucher_pool_web
    image: nginx
    ports:
        - "80:80"
    volumes:
        - ./:/code
        - ./host.conf:/etc/nginx/conf.d/default.conf
    links:
        - php:php
php:
    container_name: voucher_pool_php
    build: ./
    dockerfile: ./Dockerfile
    volumes:
        - ./:/code
    links:
        - db
db:
    container_name: voucher_pool_db
    image: mysql:5.6
    volumes:
        - /var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        - MYSQL_USER=docker
        - MYSQL_DATABASE=docker
        - MYSQL_ROOT_PASSWORD=docker
        - MYSQL_PASSWORD=docker
