-- MySQL Script generated by MySQL Workbench
-- Sat Jul 28 12:09:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema docker
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `docker` ;

-- -----------------------------------------------------
-- Schema docker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `docker` DEFAULT CHARACTER SET utf8 ;
USE `docker` ;

-- -----------------------------------------------------
-- Table `docker`.`recipients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `docker`.`recipients` ;

CREATE TABLE IF NOT EXISTS `docker`.`recipients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(80) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `docker`.`recipients` (`email` ASC);


-- -----------------------------------------------------
-- Table `docker`.`specials_offers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `docker`.`specials_offers` ;

CREATE TABLE IF NOT EXISTS `docker`.`specials_offers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `discount_percentage` DOUBLE NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `docker`.`vouchers_codes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `docker`.`vouchers_codes` ;

CREATE TABLE IF NOT EXISTS `docker`.`vouchers_codes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `offer_id` INT NOT NULL,
  `recipient_id` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `expiration_date` TIMESTAMP NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `date_usage` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_special_offers_has_recipients_special_offers`
    FOREIGN KEY (`offer_id`)
    REFERENCES `docker`.`specials_offers` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_special_offers_has_recipients_recipients1`
    FOREIGN KEY (`recipient_id`)
    REFERENCES `docker`.`recipients` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_special_offers_has_recipients_recipients1_idx` ON `docker`.`vouchers_codes` (`recipient_id` ASC);

CREATE INDEX `fk_special_offers_has_recipients_special_offers_idx` ON `docker`.`vouchers_codes` (`offer_id` ASC);

CREATE UNIQUE INDEX `code_UNIQUE` ON `docker`.`vouchers_codes` (`code` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
